### ISSUE TITLE
Glass App immediate close after launching

### ISSUE THREAD

**Issue by ennis214** [tujson/GlassEcho#1]
Thanks for your awesome development into the glass, it brings the community a lot of hope

Glass XE24
Android 10 phone

Android app does nothing when I click connect

**Comment by tujson** [comment]
Just fixed a few things and updated the README with usage instructions.

In short, Glass and your Phone need to be paired via Bluetooth before using the app (future versions will have Glass and your phone pair via the app instead of going through the settings apps). Then, open GlassEcho on Glass, then your phone. After both apps are open, click "Connect" on your phone.

**Comment by ennis214** [comment]
Working now, both Glass and Phone app, but the Glass app is not really stable, need several tries to get the app open

**Comment by tujson** [comment]
It's still in development, I'll make sure to look into Glass' stability.
